### ISSUE TITLE
Why is my container all of a sudden asking me for a .mounted in the /config path?

### ISSUE THREAD

**Issue by FadingArabChristians** [boredazfcuk/docker-icloudpd#183] opened 2022-07-17 12:40 UTC
2022-07-17 12:36:22 INFO     Sending Prowl startup notification
2022-07-17 12:36:22 INFO     Prowl startup notification sent successfully
2022-07-17 12:36:22 INFO     Download notifications: Enabled
2022-07-17 12:36:22 INFO     Delete notifications: Enabled
2022-07-17 12:36:22 INFO     Downloading from: icloud.com
2022-07-17 12:36:22 INFO     Creating directory: /root/.local/share/
2022-07-17 12:36:22 INFO     Creating symbolic link: /root/.local/share/python_keyring/ to: /config/python_keyring/ directory
2022-07-17 12:36:22 INFO     Creating group group:1000
2022-07-17 12:36:22 INFO     Creating user user:1000
2022-07-17 12:36:23 INFO     Set owner, user, on iCloud directory, if required
2022-07-17 12:36:23 INFO     Set group, group, on iCloud directory, if required
2022-07-17 12:36:23 INFO     Correct owner on icloudpd temp directory, if required
2022-07-17 12:36:23 INFO     Correct group on icloudpd temp directory, if required
2022-07-17 12:36:23 INFO     Correct owner on config directory, if required
2022-07-17 12:36:23 INFO     Correct group on config directory, if required
2022-07-17 12:36:23 INFO     Correct owner on keyring directory, if required
2022-07-17 12:36:23 INFO     Correct group on keyring directory, if required
2022-07-17 12:36:23 INFO     Set 777 permissions on iCloud directories, if required
2022-07-17 12:36:23 INFO     Set 666 permissions on iCloud files, if required
2022-07-17 12:36:23 INFO     Configure password
2022-07-17 12:36:23 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2022-07-17 12:36:23 INFO     Check download directory mounted correctly
2022-07-17 12:36:23 WARNING  Failsafe file /root/.mounted file is not present. Waiting for failsafe file to be created...

I am running the latest dockerhub version on unRaid 6.10.3

**Comment by boredazfcuk** [comment] 2022-07-17 15:06
The script now looks up the user's home folder location, rather than having `/home` hardcoded. This was done to support running the container as root.

When running as root, the script would assume the root user's home folder was `/home/root`, which is obviously wrong, as it lives in `/root`.

This caused a problem with authentication, as the keyring would be placed in `/root/.local/share/python_keyring/` but the script would look for it in `/home/root/.local/share/python_keyring/`.

If you wish to keep your download path as `/home/root/iCloud` just set the variable `download_path=/home/root/iCloud`

**Comment by knaackville** [comment] 2022-07-17 15:48
Same issue using the docker in Unraid 6.10.3, but adding the variable download_path=/home/user/iCloud/.mounted fixed that part.  

Now getting the following error:
2022-07-17 10:40:06 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
iCloud Password: 
2022-07-17 10:40:08 ERROR    Failed check for new files files
2022-07-17 10:40:08 ERROR    Error debugging info:
2022-07-17 10:40:08 ERROR    /usr/lib/python3.8/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Aborted!
2022-07-17 10:40:08 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by thatdoogieguy** [comment] 2022-07-17 16:32
@knaackville it looks like it is now trying to store create a directory in this function call that's not writable, as opposed to the defined /config/..... in Unraid.

**Comment by boredazfcuk** [comment] 2022-07-17 17:49
It it possible that the file system is read only except for the mounted locations, and you need to update your volumes? e.g.:
```
      volumes:
         - icloudpd_config:/config
         - /mnt/hd7/user/iCloud:/home/user/iCloud
```
becomes:
```
      volumes:
         - icloudpd_config:/config
         - /mnt/hd7/root/iCloud:/root/iCloud
```

**Comment by thatdoogieguy** [comment] 2022-07-17 18:15
hey @boredazfcuk so it looks like for whatever reason when making those changes it's actually deleted all existing files in the /root/iCloud folder.

In any case, a full delete of configs and images and starting again passes the authentication however it looks like the container is actively trying to store data in `/root/` directly, not the `/root/iCloud/` directory? The mounts are all correct, but there seems to be a mismatch in the container?

```
today at 14:12:332022-07-18 04:12:33 INFO     Check 2FA Cookie
today at 14:12:332022-07-18 04:12:33 INFO     Cookie exists, check expiry date
today at 14:12:332022-07-18 04:12:33 INFO     Valid two factor authentication cookie found. Days until expiration: 89
today at 14:12:332022-07-18 04:12:33 INFO     Check download directory mounted correctly
today at 14:12:332022-07-18 04:12:33 INFO     Failsafe file /root/.mounted exists, continuing
today at 14:12:332022-07-18 04:12:33 INFO     Check for new files using password stored in keyring file
today at 14:12:332022-07-18 04:12:33 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
today at 14:12:50/root/2022/07/17/IMG_1591.JPG
today at 14:12:50/root/2022/07/17/IMG_1590.PNG
today at 14:12:50/root/2022/07/17/IMG_1589.PNG
today at 14:12:50/root/2022/07/17/IMG_1588.PNG
today at 14:12:50/root/2022/07/17/IMG_1587.PNG
```


<img width="692" alt="CleanShot 2022-07-17 at 14 15 24@2x" src="https://user-images.githubusercontent.com/17012039/179419308-4b7e635c-35a3-458f-86fa-bd079e1f3013.png">

**Comment by thatdoogieguy** [comment] 2022-07-17 18:50
i ended up making this work successfully by doing the following;

- Define /config to a known path (/mnt/user/appdata/icloudpd on unraid)
- Define /root to a known path (/mnt/user/appdata/icloudpd_root on unraid)
- Create a mount /mnt/photos to a known path for photo storage (/mnt/user/photos on unraid)
- set the download_path variable to the above /mnt/user/photos path

Seems like a bit of a whack set of parameters, but it is again working as intended

**Comment by boredazfcuk** [comment] 2022-07-17 20:52
> hey @boredazfcuk so it looks like for whatever reason when making those changes it's actually deleted all existing files in the /root/iCloud folder.

It shouldn't delete anything, if you've mounted something over `/root/iCloud` and then something else over `/root`, then those last changes will win. Just unmount `/root` and the mount underneath it should reappear.

> In any case, a full delete of configs and images and starting again passes the authentication however it looks like the container is actively trying to store data in `/root/` directly, not the `/root/iCloud/` directory?

Thanks for spotting this. It was a typo in some nested parameter expansion I was doing:
`   LogInfo "Download destination directory: ${download_path:=${user_home_folder:=/home/${user}/iCloud}}"`
should have been:
`   LogInfo "Download destination directory: ${download_path:=${user_home_folder:=/home/${user}}/iCloud}"`
But I've split that now for clarity:
```
   LogInfo "User home directory: ${user_home_folder:=/home/${user}}"
   LogInfo "Download destination directory: ${download_path:=${user_home_folder}/iCloud}"
```

Now, it will start up, check the root user's home directory location, and set `${user_home_folder}` to `/root`. If the `${download_path}` variable is not specified during container creation, it will then set it to `/root/iCloud`...

However, as you're now setting `${download_path}` manually, that should no longer matter.

You should only need to set two mounts on the container. One to /config for your cookie/keyring files and one to /root for your photo data... Or if you want to move the photo data out of /root, set the download_path variable and mount your photo data volume to that location.

Originally the container only downloaded to `/home/$user/iCloud` and that could not be changed, but some users wanted to download their photos into a different location inside the container (`/download` IIRC). I have no idea why, as it makes no difference where inside the container they are downloaded to, because that folder should be a bind mount on the host, otherwise it will get destroyed each time the container is recreated... But anyway, I just added the `${download_path}` variable as a way to override the default download directory for them and it does work.

 So, I think now, if you unset `${download_path}` and only mount two volumes to /config and /root, then it should work without the /mnt/photos mount.

**Comment by knaackville** [comment] 2022-07-17 21:33
Thanks for the update.  It's progressing further, but still having an issue on my end.

I've mounted the /config folder as  /mnt/user/appdata/icloudpd 
I've also mounted /root/iCloud as /mnt/user/Photos/iCloud/user1/

I'm hesitant to mount directly to /root as I use two dockers for icloudpd to sync two different users to similar locations, specifically /mnt/user/Photos/iCloud/user1/ and /mnt/user/Photos/iCloud/user2/

It sounds like I could specify /root and the download_path to /root/user1, but I'm not sure if two instances would cause issue with sharing the /root folder.  If so, could anything being stored in /root be stored in /config instead, then define the download folder separately?   I think the workaround from @thatdoogieguy would still work for my use case if needed though.

Hopefully that makes sense!

Error log below:

2022-07-17 16:18:52 INFO     Check download directory mounted correctly
2022-07-17 16:18:52 INFO     Failsafe file /root/iCloud/.mounted exists, continuing
2022-07-17 16:18:52 INFO     Check for new files using password stored in keyring file
2022-07-17 16:18:52 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2022-07-17 16:18:54 ERROR    Failed check for new files files
2022-07-17 16:18:54 ERROR    Error debugging info:
2022-07-17 16:18:54 ERROR    Usage: icloudpd <options>

Error: Invalid value for "-d" / "--directory": Path "/root/iCloud" does not exist.
2022-07-17 16:18:54 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by timrettop** [comment] 2022-07-18 16:54
I also edited the 'Data' Path Config from /home/user/iCloud to /root/iCloud similar to above guidance and am getting the same error below.  I'm not clear on what changes we should be making to existing Unraid settings to get back up and running. 

> Error log below:
> 
> 2022-07-17 16:18:52 INFO Check download directory mounted correctly 2022-07-17 16:18:52 INFO Failsafe file /root/iCloud/.mounted exists, continuing 2022-07-17 16:18:52 INFO Check for new files using password stored in keyring file 2022-07-17 16:18:52 INFO Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time 2022-07-17 16:18:54 ERROR Failed check for new files files 2022-07-17 16:18:54 ERROR Error debugging info: 2022-07-17 16:18:54 ERROR Usage: icloudpd
> 
> Error: Invalid value for "-d" / "--directory": Path "/root/iCloud" does not exist. 2022-07-17 16:18:54 ERROR ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

**Comment by timrettop** [comment] 2022-07-18 17:32
Shouldn't the .local/share/python_keyring folder be created in /config ? seems its being created in /root where the photos are stored.

**Comment by doma2345** [comment] 2022-07-19 10:55
I am so confused.
Could someone please provide some simple instructions to getting this working in unraid
I have three instances of this running for different people and dont want to mess it up and it seems over complicated now.

**Comment by timrettop** [comment] 2022-07-19 15:31
Just checked the docker registry and there is no versioning before "latest" to try to roll back to before this last change... @boredazfcuk any chance you could revert and review as it seems that the changes have unintended consequences.

**Comment by boredazfcuk** [comment] 2022-07-19 21:20
@timrettop Yes, I'm scrapping this entirely. I just knew adding root as a user was a bad idea, mainly from a security perspective. People really should be running the container as root...

But then I do add it, against better judgement,I find that a load of people are already running it as root... WHY?!?!? lol

So, yeah, I'm just going to revert it back and leave you guys in peace.

**Comment by boredazfcuk** [comment] 2022-07-19 21:24
New version has been pushed to Dockerhub with these changes removed. Can you guys test it works please, as there are some additional (but unrelated) changes in there too. Just want to make sure that everyone is back up and running again.

**Comment by etoNcYCer** [comment] 2022-07-19 21:35
Just tried, I still get the Warning Failsafe file /home/root/ICloud/.mounted file is not present. Waiting for failsafe file to be created.

**Comment by timrettop** [comment] 2022-07-19 21:43
restored my settings with the new docker image and its working. 

/home/user/iCloud is working again.

**Comment by boredazfcuk** [comment] 2022-07-19 21:47
Awesome. I'll close this off.

**Closed by boredazfcuk** 2022-07-19 21:47 UTC
