### ISSUE TITLE
Short synchronisation_interval breaks 2FA

### ISSUE THREAD

**Issue by robflate** [boredazfcuk/docker-icloudpd#42] opened 2020-11-15 08:32 UTC
I've been running with `synchronisation_interval=10800` (3 hours) without issue. I tried to set this to a shorter period with `synchronisation_interval=900` (15 minutes) and I started getting a 2FA popup on my laptop. To fix, I changed synchronisation_interval back to 10800 and ran `docker exec -it icloudpd /usr/local/bin/sync-icloud.sh` again to reset the cookie.

My question is, is there a minimum `synchronisation_interval` before this happens? Thanks.

**Comment by boredazfcuk** [comment] 2020-11-15 09:39
I've been seeing the same thing and have an issue open upstream.

Since iOS 14 landed, I dropped the sync interval to an hour (from every 12 hours) and I started seeing these pop-ups too.

I added a login counter to the container, and I'm seeing that I'm being forced to re-confirm 2FA on the 27th login attempt. This has happened 3 times in a row.

I suspect that, although the 2FA token has a 3 month expiry time, it also has a fixed number of logins that are allowed. Having a low `synchronisation_interval` means that you're going to use up the 26 logins pretty quickly. Even syncing every hour is going to mean daily 2FA re-authorisations.

Can you check in the logs to see if yours also prompts for 2FA re-authentication on the 27th attempt, and let me know? Thanks.

**Comment by robflate** [comment] 2020-11-15 23:23
I set `synchronisation_interval=900` and it failed on the 25th attempt;

```
2020-11-15 23:02:15 INFO     iCloud login counter = 24
2020-11-15 23:02:15 INFO     Next synchronisation at 23:17
2020-11-15 23:17:15 INFO     Check 2FA Cookie
2020-11-15 23:17:15 INFO     Cookie exists, check expiry date
2020-11-15 23:17:15 INFO     Valid two factor authentication cookie found. Days until expiration: 89
2020-11-15 23:17:15 INFO     Check download directory mounted correctly
2020-11-15 23:17:15 INFO     Failsafe file /home/XXXX/iCloud/.mounted exists
2020-11-15 23:17:15 INFO     Check for new files using password stored in keyring...
0: SMS to ********XX
1: Enter two-factor authentication code
Please choose an option: [0]: Aborted!
2020-11-15 23:17:17 ERROR    Check failed - Exit code: 1
2020-11-15 23:17:17 INFO     Sending Telegram failure notification
2020-11-15 23:17:17 INFO     Telegram failure notification sent successfully
2020-11-15 23:17:17 INFO     Web cookie expires: 2021-01-14 @ 23:17:17
2020-11-15 23:17:17 INFO     Two factor authentication cookie expires: 2021-02-13 @ 08:11:04
2020-11-15 23:17:17 INFO     iCloud login counter = 25
2020-11-15 23:17:17 INFO     Next synchronisation at 23:32
```

**Comment by boredazfcuk** [comment] 2020-11-16 11:56
Pretty similar to mine, although I'd expect it to be exact. It may differ depending on whether it's downloading files or not too, I guess.

If it is Apple who is limiting downloads, as it would appear it is, then there's not going to be any other option but to increase the sync interval to once or twice a day, so that 2FA only has be re-confirmed once a week/fortnight.

It's really annoying, because it used to run for months at a time without me needing to re-confirm 2FA.

**Comment by tkunstek** [comment] 2020-11-17 03:29
Since iOS 14 I've been stuck in this 2FA loop as well. Fully deleted the container, nuked my /config folder (except .mounted) and recreated it. First time after creating the container it asks me if I want SMS, but not 2FA, even though the ENV variable is set. I hit 1 instead of 0. It asks again, but this time with the popup on my laptop. I enter the code, it smiles and says it can sync now. I start the container and it just instantly asks for the 2FA code again.

**Comment by boredazfcuk** [comment] 2020-11-21 23:49
> First time after creating the container it asks me if I want SMS, but not 2FA

This is to be expected if you've fully deleted the container's config info... When saving your password to the keyring, it only allows the option of SMS. When you confirm with the 2FA code, it saves the password to the keyring file.

The second time it asks is for 2FA (and you get the pop-up on your iDevice) is when it's actually saves the 2FA cookie to the /config directory. Once that's done, a quick restart and all should be good.

I've now pushed a new version that only allows specific values for the `synchronisation_interval` variable now. It can be set to run a maximum of every 12 hours so that 2FA should only have to be confirmed every two weeks (I hope!)

**Comment by boredazfcuk** [comment] 2021-01-27 22:28
I'm going to close this off now. The behaviour I saw where the container would stop on the 26th sync is no longer happening. One of my container's 2FA actually expired before I hit the error and I was syncing twice a day since November.

This was either an Apple change which was rolled back or some other transient issue.

**Closed by boredazfcuk** 2021-01-27 22:28 UTC
