### ISSUE TITLE
HEIC to JPG failed

### ISSUE THREAD

**Issue by Galiwyx** [boredazfcuk/docker-icloudpd#40] opened 2020-11-12 17:07 UTC
Hello,

I'm trying to convert HEIC to JPG. I used the the variable `convert_heic_to_jpeg`:. According to logs, HEIC files had been converted to JPG but not the result expected in folders : 

```
2020-11-12 18:17:40 INFO /home/user/iCloud/2019/12/IMG_0530.HEIC already exists.
2020-11-12 18:17:40 INFO All photos have been downloaded!
2020-11-12 18:17:40 INFO Convert HEIC files to JPEG
2020-11-12 18:17:40 INFO Convert HEIC to JPEG...
2020-11-12 18:17:40 INFO Synchronisation complete for user
```

![image](https://user-images.githubusercontent.com/206181/98971570-a3efb700-2511-11eb-862d-491bf7a31f30.png)
Have I forgotten something?
Thank you !

**Comment by boredazfcuk** [comment] 2020-11-12 18:15
The `convert_heic_to_jpeg` option only converts files as they are downloaded. Here's an example of one from my log earlier this afternoon:

```
2020-11-12 13:20:58 INFO     All photos have been downloaded!
2020-11-12 13:20:58 INFO     Deleting any files found in 'Recently Deleted'...
2020-11-12 13:21:00 INFO     New files downloaded: 1
2020-11-12 13:21:00 INFO     Sending Telegram downloaded files notification
2020-11-12 13:21:00 INFO     Telegram downloaded files notification sent successfully
2020-11-12 13:21:00 INFO     Convert HEIC files to JPEG
2020-11-12 13:21:00 INFO     Convert HEIC to JPEG...
2020-11-12 13:21:00 INFO     Converting /home/user/iCloud/2020/11/IMG_2205.HEIC to /home/user/iCloud/2020/11/IMG_2205.JPG
File contains 1 images
Written to /home/user/iCloud/2020/11/IMG_2205.JPG
2020-11-12 13:21:00 INFO     Timestamp of HEIC file: Thu Nov 12 12:32:07 2020
2020-11-12 13:21:00 INFO     Setting timestamp of /home/user/iCloud/2020/11/IMG_2205.JPG to Thu Nov 12 12:32:07 2020
2020-11-12 13:21:00 INFO     Synchronisation complete for user
```
If it doesn't download anything, it doesn't convert anything.

If you want to run it retrospectively for your entire library, you should connect to the container's shell, and run the command manually. e.g. (presuming container is named icloudpd):
```
docker exec -it icloudpd /bin/ash
```
then from the shell prompt, run:
```
/usr/local/bin/sync-icloud.sh --ConvertAllHEICs
```

Hope this helps.

**Comment by Galiwyx** [comment] 2020-11-12 18:34
Thank you for the explanation, but it seems doesn't work for me. 

I deleted all downloaded files and relaunched the container to force all downloads again. This is the whole log. Not a mention of converting files :  https://privatebin.net/?f9f38557e7aa1859#2VzZB6477BLX71koKe13b1Jx2gLCGtUs53FZBCJJyfBh

I'll try to run retrospectively for my entire library with your command.

**Comment by boredazfcuk** [comment] 2020-11-12 19:17
I've worked out what the issue is.

This is the bit that lists the files that need converting:
```
for heic_file in $(echo "${new_files}" | grep ".HEIC" | awk '{print $5}'); do
```
The `new_files` variable is created during the `DownloadedFilesNotification` function, so unless you have notifications enabled, it's never going to find anything.

I'll look into it.

**Comment by boredazfcuk** [comment] 2020-11-12 19:33
I've pushed a new version to Dockerhub. I think it should have fixed it...

Give it a test and let me know if it's good.

Thanks.

**Comment by Galiwyx** [comment] 2020-11-12 21:05
I deleted files and updated to the latest version` icloudpd version: 1.7.0` / `pyicloud-ipd version: 0.10.1`

Unfortunately, files are downloaded but not converted.

**Comment by Galiwyx** [comment] 2020-11-12 21:06
Woops sorry, convertions are done after all downloads.

**Comment by Galiwyx** [comment] 2020-11-12 21:35
Last question, is it possible to delete the HEIC file after the conversion in JPG ? Thanks again for this amazing tool !

**Comment by boredazfcuk** [comment] 2020-11-12 22:49
> Woops sorry, convertions are done after all downloads. Seems good !

Cool, I'll close the issue.

> Last question, is it possible to delete the HEIC file after the conversion in JPG ? Thanks again for this amazing tool !

Unfortunately not. The next time the script runs it will re-download the the HEIC file from iCloud.

However, if you delete the photo on your iDevice it will move the photo to 'Recently Deleted' on iCloud

The script will see the photo in 'Recently Deleted' and remove the HEIC file from disk. My script will not remove the JPEG however.

This probably isn't what you want as it means removing the images from iCloud too.

**Closed by boredazfcuk** 2020-11-12 22:49 UTC

**Comment by Galiwyx** [comment] 2020-11-12 22:51
Okay thank for the update, I'll try to find a solution ! Have a nice evening !
