### ISSUE TITLE
defaults not working

### ISSUE THREAD

**Issue by lonevvolf** [boredazfcuk/docker-icloudpd#605] opened 2024-07-07 07:52 UTC
Updated to the latest image from Dockerhub, and suddenly, defaults don't seem to work.  Not only did I have to add the new options to the config file, but even the folder_structure (set to folder_structure= in the config file) has suddenly starting adding files in a flat structure.

**Comment by boredazfcuk** [comment] 2024-07-07 12:54
I've just tested with latest image from Dockerhub and cannot replicate what you are describing. It creates the icloudpd.conf file and pre-populates fields with default values fine. If I set `folder_structure=` in the config file and restart the container, it repopulates the field with `folder_structure={:%Y/%m/%d}`

Only thing I can think is happening is that you're setting some Docker variable which is breaking the script that processes the config file.

**Comment by lonevvolf** [comment] 2024-07-07 13:25
A few notes that might have an effect:

1. I have a preexisting config from previous versions, most values are empty (ie. should use defaults)
2. Even after getting it working as expected, the values are not filled in in the config file for me.  They remain empty as before
3. I had to manually add the newer configs (ie. live_photo_mov_filename_policy, keep_unicode).  Otherwise I got the same issue as others reported

**Comment by boredazfcuk** [comment] 2024-07-07 14:56
1. Empty values mean those settings will be blank. The script will not use a default for empty values.

2. They should be. The startup process checks the config file and will add values for empty settings for stuff that does have defaults. E.g. if you delete the whole line for the user_id variable, or set the user_id variable to be empty, the container will edit the file and set `user_id=1000` during startup.

3. This should not happen. You should be able to delete any line in the config file, restart the container, and find that entry reappears in the config file. Certain configuration items will set default values too.

Something must be breaking this process in your environment. Try removing the 1st line of the config file and restarting the container. Does that variable reappear after the restart? Try the 10th line and restart?

**Comment by lonevvolf** [comment] 2024-07-07 16:15
Just to be clear, this is not a new config file - I've had it for over a year.  It never filled in default values.  The file was generated by the application itself - I never created it.

Removing the first line (agentid=) doesn't change anything.  Same for the 10th line (content_source_url=)
Removing the entire file gives an error: Failed to create configuration file

**Comment by boredazfcuk** [comment] 2024-07-07 18:39
> It never filled in default values.

Originally it didn't, but as of about 10 versions ago, it does.

> Removing the first line (agentid=) doesn't change anything.  Same for the 10th line (content_source_url=)
> 
> Removing the entire file gives an error: Failed to create configuration file

Then something must have changed regarding your setup. At some point, it was allowed to create the config file and did, but now it isn't, so can't update it with missing values or create a new one if you remove it entirely.

**Comment by lonevvolf** [comment] 2024-07-07 20:49
That's very odd, since it's able to create other files in that folder, like the token tracking, etc.  I will experiment a bit more...

**Comment by boredazfcuk** [comment] 2024-07-07 22:54
Try creating a test container with something like:
```
   icloudpd_test:
      hostname: icloudpd_test
      container_name: icloudpd_test
      environment:
         - TZ=Europe/UTC
      image: boredazfcuk/icloudpd
```

When it starts up it will just hang as it won't find a .mounted failsafe. It'll just error and reboot every 2mins. You should see it creates a semi-populated /config/icloudpd.conf file. Delete a couple of lines and some of the default values. Restart the container and watch them re-appear.

**Comment by THX723** [comment] 2024-07-11 05:12
I also ran into this issue after updating to the latest release a couple days ago. It's been working fine through all the updates for more than a year. It all ran fine again when I had to manually define 'user=' and 'download_path='. I've always had those blanked and it would just assume the default value. This release did not work unless I explicitly define the default value.

**Comment by THX723** [comment] 2024-07-11 05:34
Uncovered more issues with missing defaults for:

keep_unicode
live_photo_mov_filename_policy

**Comment by boredazfcuk** [comment] 2024-07-11 13:06
> I'm wondering if this has anything to do with me not having skipped several updates. It appears those variable were newly introduced since my previous update.

Shouldn't be. Every time the container is started, it processes the config file as follows:-

1) Does "variable1=" appear in the config file? Yes - move on. No - add to config file using the value specified in the equivalent Docker environment variable. If no Docker variable exists it will set a default value, in certain cases (i.e. I can't set a default value for **apple_id** but I can for **authentication_type**)
1a) Repeat above line for all variables

2) Is "variable1=" in the config file, but blank? No - move on. Yes - set default value if possible (e.g. **auto_delete=false**)
2a) Repeat above line for all variables

3) Is "variable1" set as a Docker environment variables? No - move on. Yes - update the config file variable so it's the same as the Docker variable

Step 1 creates the config file if it does not exist. It also adds any variables that are missing, giving them a default value or the value specified in the Docker environment variable.
Step 2 sets default/expected values for variables that may be missing them.
Step 3 sets/overwrites values for variables if those variables are specified as Docker environment variables.

It does this every time the container is restarted, so if lines are deleted, they will return with the expected/default value. If a value is blank when it shouldn't be, it will add the expected/default. If a Docker environment variable is added/changed during a container re-creation, it will use that to set the same value in the config file.

The only thing I can think is that everyone who has reported this issue is setting a Docker environment variable that the script cannot process. The script then crashes and hands over to the main synchronisation script leaving an incomplete config file.

>live_photo_size

Pretty sure that the **live_photo_size** variable has been around since the early days.


> Try creating a test container with something like:
> 
> ```
>    icloudpd_test:
>       hostname: icloudpd_test
>       container_name: icloudpd_test
>       environment:
>          - TZ=Europe/UTC
>       image: boredazfcuk/icloudpd
> ```
> 
> When it starts up it will just hang as it won't find a .mounted failsafe. It'll just error and reboot every 2mins. You should see it creates a semi-populated /config/icloudpd.conf file. Delete a couple of lines and some of the default values. Restart the container and watch them re-appear.

Has anyone who's having a problem actually tried this yet?

**Comment by THX723** [comment] 2024-07-11 17:11
I'll test that out this weekend.

**Comment by BigOrange666** [comment] 2024-07-13 07:52
I updated the latest image and used the configuration file before the update to start the container.version : 1.0.906_10-07-2024. It prompted that the apple id was not set. I found that "icloudpd.conf" was not recognized. Even after deleting all files and rebuilding the container, no new configuration file was created.

> Try creating a test container with something like:
> 
> ```
>    icloudpd_test:
>       hostname: icloudpd_test
>       container_name: icloudpd_test
>       environment:
>          - TZ=Europe/UTC
>       image: boredazfcuk/icloudpd
> ```
> 
> When it starts up it will just hang as it won't find a .mounted failsafe. It'll just error and reboot every 2mins. You should see it creates a semi-populated /config/icloudpd.conf file. Delete a couple of lines and some of the default values. Restart the container and watch them re-appear.

I tried this image. No configuration file was created. I tried adding parameters to the environment variables and it worked, so the problem is that the configuration file is invalid. Could you please help check it? Thanks a lot

**Comment by lonevvolf** [comment] 2024-07-21 14:26
Sorry for the silence from my end here - I just got back from a longer vacation.
I updated to the latest image today, and got a new error:
`PermissionError: [Errno 13] Permission denied: '/config/<myemail>.session'`

After reviewing settings, I realized that my user on the host system is a member of both "users" and "administrators" groups.  In the config, I was specifying the users group_id and name.  I changed to the administrators name and id, then that error was resolved.  Copying my vacation photos now, then I will try a fresh image test as requested before.

**Comment by lonevvolf** [comment] 2024-07-21 14:58
> Try creating a test container with something like:
> 
>    icloudpd_test:
>       hostname: icloudpd_test
>       container_name: icloudpd_test
>       environment:
>          - TZ=Europe/UTC
>       image: boredazfcuk/icloudpd
> When it starts up it will just hang as it won't find a .mounted failsafe. It'll just error and reboot every 2mins. You should see it creates a semi-populated /config/icloudpd.conf file. Delete a couple of lines and some of the default values. Restart the container and watch them re-appear.

I tried this - it tells me "Apple ID not set - exiting".
Interestingly, it also says: "Loading configuration from /icloudpd.conf" which looks like it's trying to load from root instead of /config?
No default file is created in the mapped folder.

**Comment by boredazfcuk** [comment] 2024-07-21 20:36
>"Loading configuration from /icloudpd.conf"

I set an environment variable when building the container config_dir=/config then I tell the container that the location of the config file is $config_dir/icloudpf.conf

It seems like your system must be unsetting the $config_dir variable somehow.

Also, if your system couldn't find the config file, it would not get to the part where it checks for the failsafe. The first thing the script does is check the config file exists, and if not, it exits immediately. Your config file must exist at /icloudpd.conf.

What system are you using this on?

**Comment by lonevvolf** [comment] 2024-07-21 20:53
I am on Synology.
I had removed the default variables, to match what was posted above.  I now added config_dir back, and it created the config file.  Note that many of the values in the newly created config file are empty - it looks very similar to my old file.

**Comment by boredazfcuk** [comment] 2024-07-21 21:00
The config_dir variable is configured as /config during container build. It should exist in the container as /config if you do not set it.

**Comment by lonevvolf** [comment] 2024-07-21 21:08
Yes, I see now that I should have left those defaults - that's my mistake.  I put all of them back now and let it recreate the config file.  It looks the same as before.  Keep in mind I am referring here to the test container, not my main one.
Deleting the first line (agentid=) and rerunning the test container **does** readd it.
I would note that in order to be able to edit the file on the host, I have to edit the permissions to add inherited permissions from the parent folder.  I haven't tried updating the userid/groupid there though.

**Comment by boredazfcuk** [comment] 2024-07-21 21:30
>Edit: I've pushed a new version in which I've eliminated the config_dir variable entirely. I've hard-coded it as /config everywhere now so it should fix the issue. Might break it for any people who are setting it to be something different, but I'm guessing those people are few and far between.

Ignore that. I've just realised that the latest version did not build and failed with an error. The x86 versions worked OK, as I only build that one for my test environments. When I built with additional architectures like ARM, it failed to build the Python cffi package. I'll need to investigate and see if I can get it working.

**Comment by boredazfcuk** [comment] 2024-07-21 22:40
New versions finally pushed to Dockerhub.

**Comment by boredazfcuk** [comment] 2024-07-23 19:26
Just closing this off as I believe it's resolved now.

**Closed by boredazfcuk** 2024-07-23 19:26 UTC
