### ISSUE TITLE
icloudpd.conf is overwritten to default settings each time the container is started

### ISSUE THREAD

**Issue by afreuden** [boredazfcuk/docker-icloudpd#419] opened 2023-10-28 12:36 UTC
Hi,
Am experiencing an issue where after I have added my Apple ID and other settings to icloudpd.conf and started the container, the config file is wiped to the default settings and exits at:

```
2023-10-28 22:25:45 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.684 started *****
2023-10-28 22:25:45 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-10-28 22:25:45 INFO     Alpine Linux 3.18.3
2023-10-28 22:25:45 INFO     Python version: 3.11.5
2023-10-28 22:25:46 INFO     Loading configuration from: /config/icloudpd.conf
2023-10-28 22:25:46 ERROR    Apple ID not set - exiting
```

I tried setting icloudpd.conf to read only but then I get this:
```

2023-10-28 22:31:52 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.684 started *****
2023-10-28 22:31:52 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-10-28 22:31:52 INFO     Alpine Linux 3.18.3
2023-10-28 22:31:52 INFO     Python version: 3.11.5
/usr/local/bin/sync-icloud.sh: line 5: can't create /config/icloudpd.conf: Read-only file system
mv: cannot move '/config/icloudpd.conf' to '/config/icloudpd.conf.tmp': Read-only file system
sort: cannot read: /config/icloudpd.conf.tmp: No such file or directory
chmod: failed to get attributes of '/config/icloudpd.conf.tmp': No such file or directory
rm: cannot remove '/config/icloudpd.conf.tmp': No such file or directory
sed: can't create temp file '/config/icloudpd.confXXXXXX': Read-only file system
sed: can't create temp file '/config/icloudpd.confXXXXXX': Read-only file system
sed: can't create temp file '/config/icloudpd.confXXXXXX': Read-only file system
2023-10-28 22:31:52 INFO     Loading configuration from: /config/icloudpd.conf
2023-10-28 22:31:52 ERROR    Apple ID not set - exiting
```

**Comment by boredazfcuk** [comment] 2023-11-12 21:24
I think I saw this in testing. It was due to there being a special character in the config file/environment variables... a quotation mark, or an apostrophe, or something like that. It mean that the commands I was running to build the file would error out part way through and half the variables were not being updated.

**Comment by boredazfcuk** [comment] 2024-05-05 15:36
Closing as can't reproduce. Looks like permissions issue to be honest.

**Closed** 2024-05-05 15:35 UTC
