### ISSUE TITLE
Select album for download

### ISSUE THREAD

**Issue by FrankHdf** [boredazfcuk/docker-icloudpd#162] opened 2022-05-20 05:59 UTC
Hello,
would it be possible to make icloudpd's --album option available? I would like to download just one album, not all of my photos.
This would be really great.
Thanks

**Comment by boredazfcuk** [comment] 2022-05-20 20:30
Hi,

I've pushed a new version to Dockerhub which allows you to configure the name of the album using the **photo_album** variable. Can you test it and let me know if it works? I've not tested it myself, but it was a pretty simple update so I think it should be fine.

Thanks.

**Comment by FrankHdf** [comment] 2022-05-21 10:35
Thanks a lot, it works like a charm :-)
One question: at the beginning of the sync process each time a complete list of all photos is downloaded. Is this by design? I ask because this takes approx. an hour for me, I have a lot of photos in the iCloud. Or can this be changed?
Thanks

**Comment by boredazfcuk** [comment] 2022-05-21 10:56
Yes, this is by design. It's so it can check whether new files actually exist before starting a download run. If you wish to disable this behaviour, set the **skip_check** variable to `True`

**Comment by boredazfcuk** [comment] 2022-07-16 13:01
Hi,

I've closed this off as I pushed the change ages back.

Thanks.

**Closed** 2022-07-16 13:00 UTC
